version: '3.8'
services:

  adminer:
    image: adminer
    container_name: STP-adminer
    restart: always
    ports:
      - 8080:8080
  
  backend:
    container_name: STP-Backend-server
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/server.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .

  frontend:
    container_name: STP-Frontend-server
    build:
      context: frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './frontend:/app:cached'
      - './frontend/node_modules:/app/node_modules:cached'
    environment:
      - NODE_ENV=development