const CREATE_STREAM = 'CREATE_STREAM';
const FETCH_STREAMS = 'FETCH_STREAMS';
const FETCH_STREAM = 'FETCH_STREAM';
const DELETE_STREAM = 'DELETE_STREAM';
const EDIT_STREAM = 'EDIT_STREAM';
const SIGN_IN = 'SIGN_IN';
const SIGN_OUT = 'SIGN_OUT';
// eslint-disable-next-line
export default { CREATE_STREAM , FETCH_STREAMS , SIGN_IN , SIGN_OUT , FETCH_STREAM, DELETE_STREAM, EDIT_STREAM }