const CREATE_IMAGE = 'CREATE_IMAGE';
const FETCH_IMAGE = 'FETCH_IMAGE';
const FETCH_ALL_IMAGE = 'FETCH_ALL_IMAGE';
const UPDATE_IMAGE = 'UPDATE_IMAGE';
const DELETE_IMAGE = 'DELETE_IMAGE';

// eslint-disable-next-line
export default { 
    CREATE_IMAGE,
    FETCH_IMAGE,
    FETCH_ALL_IMAGE,
    UPDATE_IMAGE,
    DELETE_IMAGE
 }